In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [44]:
training_data=pd.read_csv(r"car.data",header=None)

In [45]:
training_data

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [4]:
training_data.columns=["BUYING","MAINT","DOORS","PERSONS",'LUG_BOOT','SAFETY',"CLASSES"]

In [5]:
training_data.head()

BUYING  MAINT DOORS PERSONS LUG_BOOT SAFETY CLASSES
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [6]:
training_data.isnull().sum()

BUYING      0
MAINT       0
DOORS       0
PERSONS     0
LUG_BOOT    0
SAFETY      0
CLASSES     0
dtype: int64

In [7]:
colname=[]
for x in training_data.columns:
    if training_data[x].dtypes=='object':
        colname.append(x)
colname

['BUYING', 'MAINT', 'DOORS', 'PERSONS', 'LUG_BOOT', 'SAFETY', 'CLASSES']

In [8]:
# for preprocessing the data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    
    le_name_mapping=dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('Mapping', le_name_mapping)
    
# alphabet arrangement

Feature BUYING
Mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature MAINT
Mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature DOORS
Mapping {'2': 0, '3': 1, '4': 2, '5more': 3}
Feature PERSONS
Mapping {'2': 0, '4': 1, 'more': 2}
Feature LUG_BOOT
Mapping {'big': 0, 'med': 1, 'small': 2}
Feature SAFETY
Mapping {'high': 0, 'low': 1, 'med': 2}
Feature CLASSES
Mapping {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


# # # feature classes
#'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3

In [9]:
training_data.head()

BUYING  MAINT  DOORS  PERSONS  LUG_BOOT  SAFETY  CLASSES
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [10]:
x=training_data.values[:,0:-1]
y=training_data.values[:,-1]

In [11]:
x.shape

(1728, 6)

In [12]:
y.shape

(1728,)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
x=scaler.transform(x)

In [14]:
print(x)

[[ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  0.        ]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487  1.22474487]
 [ 1.34164079  1.34164079 -1.34164079 -1.22474487  1.22474487 -1.22474487]
 ...
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  0.        ]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487  1.22474487]
 [-0.4472136  -0.4472136   1.34164079  1.22474487 -1.22474487 -1.22474487]]


In [15]:
from sklearn.model_selection import train_test_split
# split the data into test and train
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=10)

# test_size is 20% for less than 1000 observations and greater than 1000 30%

In [16]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1382, 6)
(1382,)
(346, 6)
(346,)


# running a decision tree 

In [17]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(random_state=10)

# fit the model on data and predict the values

model_DecisionTree.fit(x_train,y_train)

y_pred=model_DecisionTree.predict(x_test)

#print(y_pred)
print(list(zip(y_test,y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (1, 1), (3, 3), (1, 1), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (3, 1), (2, 2), (2, 2), (2, 2), (1, 1), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 1), (2, 2), (2, 2), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 1),

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 61   2   1   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  1   2   0  15]]
classification report: 
              precision    recall  f1-score   support

           0       0.98      0.95      0.97        64
           1       0.76      1.00      0.87        13
           2       1.00      1.00      1.00       251
           3       1.00      0.83      0.91        18

    accuracy                           0.98       346
   macro avg       0.94      0.95      0.94       346
weighted avg       0.99      0.98      0.98       346

accuracy of the model:  0.9826589595375722


In [19]:
# for feature selection or vaible selection can be checnked

In [20]:
print(list(zip(training_data.columns[0:-1],model_DecisionTree.feature_importances_)))

[('BUYING', 0.15597110143170986), ('MAINT', 0.2429065249534759), ('DOORS', 0.0493216578497735), ('PERSONS', 0.19983155234249397), ('LUG_BOOT', 0.10205408060463227), ('SAFETY', 0.24991508281791455)]


In [21]:
training_data.columns[:-1]

Index(['BUYING', 'MAINT', 'DOORS', 'PERSONS', 'LUG_BOOT', 'SAFETY'], dtype='object')

In [22]:
# prediction using random foreset classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10)
# fit the model in the data and predict the values

model_RandomForest.fit(x_train,y_train)
y_pred=model_RandomForest.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 63   1   0   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  1   0   0  17]]
classification report: 
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        64
           1       0.93      1.00      0.96        13
           2       1.00      1.00      1.00       251
           3       1.00      0.94      0.97        18

    accuracy                           0.99       346
   macro avg       0.98      0.98      0.98       346
weighted avg       0.99      0.99      0.99       346

accuracy of the model:  0.9942196531791907


In [25]:
# extra trees classifer

In [26]:
from sklearn.ensemble import ExtraTreesClassifier
model_ExtraTrees=ExtraTreesClassifier(n_estimators=100,random_state=10)
# fit the model in the data and predict the values

model_ExtraTrees.fit(x_train,y_train)
y_pred=model_ExtraTrees.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 62   1   0   1]
 [  2  11   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
classification report: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        64
           1       0.92      0.85      0.88        13
           2       1.00      1.00      1.00       251
           3       0.95      1.00      0.97        18

    accuracy                           0.99       346
   macro avg       0.96      0.95      0.96       346
weighted avg       0.99      0.99      0.99       346

accuracy of the model:  0.9884393063583815


In [28]:
# using adaboost classifier

In [29]:
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10), n_estimators=100,random_state=10)


# fit the model in the data and predict the values

model_AdaBoost.fit(x_train,y_train)
y_pred=model_AdaBoost.predict(x_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 61   2   1   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  1   2   0  15]]
classification report: 
              precision    recall  f1-score   support

           0       0.98      0.95      0.97        64
           1       0.76      1.00      0.87        13
           2       1.00      1.00      1.00       251
           3       1.00      0.83      0.91        18

    accuracy                           0.98       346
   macro avg       0.94      0.95      0.94       346
weighted avg       0.99      0.98      0.98       346

accuracy of the model:  0.9826589595375722


In [31]:
 # using gradient boosting classifier

In [32]:
from sklearn.ensemble import GradientBoostingClassifier
model_GradientBoosting=GradientBoostingClassifier(n_estimators=100,random_state=10)
# fit the model in the data and predict the values

model_GradientBoosting.fit(x_train,y_train)
y_pred=model_GradientBoosting.predict(x_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 63   1   0   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        64
           1       0.93      1.00      0.96        13
           2       1.00      1.00      1.00       251
           3       1.00      1.00      1.00        18

    accuracy                           1.00       346
   macro avg       0.98      1.00      0.99       346
weighted avg       1.00      1.00      1.00       346

accuracy of the model:  0.9971098265895953


In [ ]:
pip install xgboost

In [35]:
from xgboost import XGBClassifier
model_XGB=XGBClassifier(n_estimators=100,random_state=10)
# fit the model in the data and predict the values

model_XGB.fit(x_train,y_train)
y_pred=model_XGB.predict(x_test)

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 61   2   1   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        64
           1       0.87      1.00      0.93        13
           2       1.00      1.00      1.00       251
           3       1.00      1.00      1.00        18

    accuracy                           0.99       346
   macro avg       0.97      0.99      0.98       346
weighted avg       0.99      0.99      0.99       346

accuracy of the model:  0.9913294797687862


In [37]:
from xgboost import XGBClassifier
model_XGB=XGBClassifier(n_estimators=200,random_state=10)
# fit the model in the data and predict the values

model_XGB.fit(x_train,y_train)
y_pred=model_XGB.predict(x_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 63   1   0   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        64
           1       0.93      1.00      0.96        13
           2       1.00      1.00      1.00       251
           3       1.00      1.00      1.00        18

    accuracy                           1.00       346
   macro avg       0.98      1.00      0.99       346
weighted avg       1.00      1.00      1.00       346

accuracy of the model:  0.9971098265895953


In [39]:
from sklearn.ensemble import GradientBoostingClassifier
model_GradientBoosting=GradientBoostingClassifier(n_estimators=200,random_state=10)
# fit the model in the data and predict the values

model_GradientBoosting.fit(x_train,y_train)
y_pred=model_GradientBoosting.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 64   0   0   0]
 [  0  13   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        64
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00       251
           3       1.00      1.00      1.00        18

    accuracy                           1.00       346
   macro avg       1.00      1.00      1.00       346
weighted avg       1.00      1.00      1.00       346

accuracy of the model:  1.0


In [41]:
from sklearn.ensemble import GradientBoostingClassifier
model_GradientBoosting=GradientBoostingClassifier(n_estimators=200,random_state=10)
# fit the model in the data and predict the values

model_GradientBoosting.fit(x_train,y_train)
y_pred=model_GradientBoosting.predict(x_test)