In [15]:
import pandas as pd
training_data=pd.read_excel(r"titanic_df.xlsx",index_col=0,header=0)
print(training_data.shape)
training_data

(891, 11)


Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
# feature selection

In [24]:
training_data=training_data[['Name','Pclass','Sex','Age','Survived']]
print(training_data.shape)

(891, 5)


In [25]:
training_data.describe(include='all')

Name      Pclass   Sex         Age    Survived
count                       891  891.000000   891  891.000000  891.000000
unique                      891         NaN     2         NaN         NaN
top     Braund, Mr. Owen Harris         NaN  male         NaN         NaN
freq                          1         NaN   577         NaN         NaN
mean                        NaN    2.308642   NaN   29.560236    0.383838
std                         NaN    0.836071   NaN   13.005010    0.486592
min                         NaN    1.000000   NaN    0.420000    0.000000
25%                         NaN    2.000000   NaN   22.000000    0.000000
50%                         NaN    3.000000   NaN   29.000000    0.000000
75%                         NaN    3.000000   NaN   35.000000    1.000000
max                         NaN    3.000000   NaN   80.000000    1.000000

In [26]:
# finding of mssinf values   preproccesing step no 2

In [27]:
print(training_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [28]:
# importing missing data with mean value
training_data['Age'].fillna(int(training_data['Age'].mean()),inplace=True)
print(training_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [29]:
# transforming the categorical data into numerical

In [31]:
from sklearn import preprocessing
colname=['Sex']
le=preprocessing.LabelEncoder()
for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    
    
# traing_data['Sex']=traing_data['Sex'].map

In [33]:
print(training_data.head())

                                                          Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0  


In [37]:
# creating x and y

x_train=training_data.values[0:870,1:-1]
y_train=training_data.values[0:870,-1]
y_train=y_train.astype(int)


x_test=training_data.values[870:,1:-1]
y_test=training_data.values[870:,-1]
y_test=y_test.astype(int)

In [38]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(870, 3)
(870,)
(21, 3)
(21,)


In [40]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

scaler.fit(x_train)
#scaler.fit_tranform(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [41]:
x_train

array([[ 0.82810204,  0.73472649, -0.5784206 ],
       [-1.56541549, -1.3610507 ,  0.64650051],
       [ 0.82810204, -1.3610507 , -0.27219032],
       ...,
       [-1.56541549,  0.73472649,  0.11059753],
       [ 0.82810204,  0.73472649, -0.04251761],
       [ 0.82810204,  0.73472649, -1.95645684]])

# PREDICTING THE MODEL BASED ON KNN

In [ ]:
pip install sklearn

In [55]:
# PREDICTING USING THE kneighbors_classfier

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(x_train))),
                               metric='euclidean')

#euclidean,manhatatan,min kowski
#fit the model in data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 0), (0, 0)]


In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[13  1]
 [ 2  5]]
classification report: 
              precision    recall  f1-score   support

           0       0.87      0.93      0.90        14
           1       0.83      0.71      0.77         7

    accuracy                           0.86        21
   macro avg       0.85      0.82      0.83        21
weighted avg       0.86      0.86      0.85        21

accuracy of the model:  0.8571428571428571


# PREDICTING THE MODEL ON EXTERNAL DTAA

In [58]:
row={'Pclass':2,
    'Sex':1,
    'Age':60}
# convert into a datagrame
test_data=pd.DataFrame(data=row,index=[0])
test_data

Pclass  Sex  Age
0       2    1   60

In [59]:
test_data=scaler.transform(test_data)
test_data

array([[-0.36865672,  0.73472649,  2.33076704]])

In [60]:
y_pred_temp=model_KNN.predict(test_data)
y_pred_temp

array([0])

# working on k

In [73]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN=KNeighborsClassifier(n_neighbors=K,metric='euclidean')
    
#euclidean,manhattan,min kowski
# fit the model in the data and predict the values

    model_KNN.fit(x_train,y_train)
    y_pred=model_KNN.predict(x_test)
    print('Accuracy is ', accuracy_score(y_test,y_pred),'for k=value',K)
    my_dict[K]=accuracy_score(y_test,y_pred)

Accuracy is  0.7619047619047619 for k=value 1
Accuracy is  0.8095238095238095 for k=value 2
Accuracy is  0.8095238095238095 for k=value 3
Accuracy is  0.8571428571428571 for k=value 4
Accuracy is  0.8571428571428571 for k=value 5
Accuracy is  0.8095238095238095 for k=value 6
Accuracy is  0.8095238095238095 for k=value 7
Accuracy is  0.8571428571428571 for k=value 8
Accuracy is  0.8095238095238095 for k=value 9
Accuracy is  0.9047619047619048 for k=value 10
Accuracy is  0.8571428571428571 for k=value 11
Accuracy is  0.9047619047619048 for k=value 12
Accuracy is  0.9047619047619048 for k=value 13
Accuracy is  0.8571428571428571 for k=value 14
Accuracy is  0.9047619047619048 for k=value 15
Accuracy is  0.8571428571428571 for k=value 16
Accuracy is  0.8571428571428571 for k=value 17
Accuracy is  0.8095238095238095 for k=value 18
Accuracy is  0.8571428571428571 for k=value 19
Accuracy is  0.8095238095238095 for k=value 20
Accuracy is  0.8095238095238095 for k=value 21
Accuracy is  0.8571428

In [74]:
my_dict


{1: 0.7619047619047619,
 2: 0.8095238095238095,
 3: 0.8095238095238095,
 4: 0.8571428571428571,
 5: 0.8571428571428571,
 6: 0.8095238095238095,
 7: 0.8095238095238095,
 8: 0.8571428571428571,
 9: 0.8095238095238095,
 10: 0.9047619047619048,
 11: 0.8571428571428571,
 12: 0.9047619047619048,
 13: 0.9047619047619048,
 14: 0.8571428571428571,
 15: 0.9047619047619048,
 16: 0.8571428571428571,
 17: 0.8571428571428571,
 18: 0.8095238095238095,
 19: 0.8571428571428571,
 20: 0.8095238095238095,
 21: 0.8095238095238095,
 22: 0.8571428571428571,
 23: 0.8095238095238095,
 24: 0.8095238095238095,
 25: 0.8095238095238095,
 26: 0.8571428571428571,
 27: 0.8571428571428571,
 28: 0.8571428571428571,
 29: 0.8571428571428571,
 30: 0.8571428571428571}

In [76]:
for K in my_dict:
    if my_dict[K]==max(my_dict.values()):
        print(K, ":",my_dict[K])

10 : 0.9047619047619048
12 : 0.9047619047619048
13 : 0.9047619047619048
15 : 0.9047619047619048


In [81]:
# with k =10
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=10,
                               metric='euclidean')

#euclidean,manhatatan,min kowski
#fit the model in data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [82]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[12  2]
 [ 0  7]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

accuracy of the model:  0.9047619047619048


In [83]:
# with k =10
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=12,
                               metric='euclidean')

#euclidean,manhatatan,min kowski
#fit the model in data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[12  2]
 [ 0  7]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

accuracy of the model:  0.9047619047619048


In [85]:
# with k =13
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=13,
                               metric='euclidean')

#euclidean,manhatatan,min kowski
#fit the model in data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[12  2]
 [ 0  7]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

accuracy of the model:  0.9047619047619048


In [86]:
# with k =15
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=15,
                               metric='euclidean')

#euclidean,manhatatan,min kowski
#fit the model in data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[12  2]
 [ 0  7]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

accuracy of the model:  0.9047619047619048
